### ISSUE TITLE
Hangman game

### ISSUE THREAD

**Issue by koman2019** [koman2019/web-rss-reader#1]
Task:
 - Get contents from one article the user saved.
 - Pick one "meaningful" word from the selected article.
 - Play the hangman game (the life element is based on his input or .... )
 - Focus on php part

- feasible: one function for getting the word, one function for game

**Comment by cstsangac** [comment]
noted. good idea. will work on this part.

**Comment by cstsangac** [comment]
use playing.php and hangman.php?

**Comment by cstsangac** [comment]
how about api for english word lookup, "WordsAPI" that u suggested was not good, cant set that up. 
how about Oxford Dictionary API? Tried that, looking good.

**Comment by koman2019** [comment]
Okay go ahead.

**Comment by koman2019** [comment]
The hangman first version works now, 
The branches are playing-page-hangman-*
